const TYPE = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",
  VERIFY_FAIL: "VERIFY_FAIL",
  SET_PROFILE_SUCCESS: "SET_PROFILE_SUCCESS",
  SET_PROFILE_FAIL: "SET_PROFILE_FAIL",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAIL: "GET_PROFILE_FAIL",
  IS_LOADING_USER: "IS_LOADING_USER",
  LOGOUT: "LOGOUT",
};

export default TYPE;
